// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prqwtmghtcebajepdinn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycXd0bWdodGNlYmFqZXBkaW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDc3NzEsImV4cCI6MjA2OTcyMzc3MX0.TPNwm33DszcXvcXBXF61rU-EIDJqq_3klTU04Y5LQKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});